import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { CURRENT_USER } from "@/constants/mock-data";
import { useColors } from "@/hooks/use-colors";
import {
  AREA_OPTIONS, CUISINE_OPTIONS, createDefaultPreferences, DEFAULT_AI_CONSENTS, DEFAULT_SAFETY_PREFERENCES,
  loadMemberAiConsents, loadMemberPreferences, loadMemberSafetyPreferences, recordActivityEvent,
  saveMemberAiConsents, saveMemberPreferences, saveMemberSafetyPreferences, validatePreferences,
  type MemberAiConsents, type MemberPreferences, type MemberSafetyPreferences,
} from "@/lib/ai-data-store";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, Switch, Text, TextInput, View } from "react-native";

const DAY_OPTIONS = [{ key: "weekday", label: "平日" }, { key: "saturday", label: "土曜" }, { key: "sunday_holiday", label: "日曜・祝日" }, { key: "irregular", label: "不定期" }] as const;
const TIME_OPTIONS = [{ key: "lunch", label: "ランチ" }, { key: "afternoon", label: "午後" }, { key: "dinner", label: "ディナー" }, { key: "late_night", label: "夜遅め" }] as const;
const SIZE_OPTIONS = [{ key: "small", label: "4〜6人" }, { key: "medium", label: "7〜12人" }, { key: "large", label: "13人以上" }, { key: "any", label: "こだわらない" }] as const;
const EVENT_TYPE_OPTIONS = [{ key: "regular_dining", label: "食事会" }, { key: "hard_to_book", label: "予約困難店" }, { key: "wine", label: "ワイン" }, { key: "sweets", label: "スイーツ" }, { key: "travel", label: "旅行" }, { key: "club_activity", label: "部活動" }, { key: "party", label: "交流会" }] as const;
const GOAL_OPTIONS = [{ key: "food_discovery", label: "美味しいお店を発見" }, { key: "make_friends", label: "友達を作る" }, { key: "find_hobby_friends", label: "趣味仲間を探す" }, { key: "new_experiences", label: "新しい体験" }, { key: "networking", label: "交流を広げる" }, { key: "learn_about_food", label: "食を学ぶ" }] as const;

function Card({ title, description, children }: { title: string; description?: string; children: React.ReactNode }) {
  const colors = useColors(); return <View style={{ backgroundColor: colors.surface, borderRadius: 16, padding: 16, marginBottom: 14 }}><Text style={{ fontSize: 16, fontWeight: "900", color: colors.foreground }}>{title}</Text>{description ? <Text style={{ fontSize: 12, lineHeight: 18, color: colors.muted, marginTop: 4, marginBottom: 12 }}>{description}</Text> : <View style={{ height: 10 }} />}{children}</View>;
}

function Chips({ options, values, max, onChange }: { options: readonly { key: string; label: string }[]; values: string[]; max?: number; onChange: (values: string[]) => void }) {
  const colors = useColors(); return <View style={{ flexDirection: "row", flexWrap: "wrap", gap: 8 }}>{options.map((option) => { const selected = values.includes(option.key); return <Pressable key={option.key} onPress={() => { if (selected) onChange(values.filter((item) => item !== option.key)); else if (!max || values.length < max) onChange([...values, option.key]); else Alert.alert(`最大${max}個まで選択できます`); }} style={{ borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8, backgroundColor: selected ? "#F9E4ED" : colors.background, borderWidth: 1, borderColor: selected ? "#D65E8D" : colors.border }}><Text style={{ fontSize: 13, fontWeight: selected ? "800" : "600", color: selected ? "#B44772" : colors.foreground }}>{selected ? "✓ " : ""}{option.label}</Text></Pressable>; })}</View>;
}

function ConsentRow({ label, detail, value, onChange }: { label: string; detail: string; value: boolean; onChange: (value: boolean) => void }) {
  const colors = useColors(); return <View style={{ flexDirection: "row", alignItems: "center", paddingVertical: 11, borderTopWidth: 0.5, borderTopColor: colors.border }}><View style={{ flex: 1, paddingRight: 12 }}><Text style={{ fontSize: 14, fontWeight: "800", color: colors.foreground }}>{label}</Text><Text style={{ fontSize: 11, lineHeight: 16, color: colors.muted, marginTop: 3 }}>{detail}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: "#E8A0BF" }} /></View>;
}

export default function AiSettingsScreen() {
  const colors = useColors(); const router = useRouter();
  const [preferences, setPreferences] = useState<MemberPreferences>(() => createDefaultPreferences({ residence: CURRENT_USER.residence, favoriteCuisines: CURRENT_USER.favoriteCuisines }));
  const [consents, setConsents] = useState<MemberAiConsents>(DEFAULT_AI_CONSENTS); const [safety, setSafety] = useState<MemberSafetyPreferences>(DEFAULT_SAFETY_PREFERENCES); const [saving, setSaving] = useState(false);
  useEffect(() => { void Promise.all([loadMemberPreferences(CURRENT_USER.id, { residence: CURRENT_USER.residence, favoriteCuisines: CURRENT_USER.favoriteCuisines }), loadMemberAiConsents(CURRENT_USER.id), loadMemberSafetyPreferences(CURRENT_USER.id)]).then(([p, c, s]) => { setPreferences(p); setConsents(c); setSafety(s); }); }, []);
  const save = async () => { const error = validatePreferences(preferences); if (error) return Alert.alert("入力内容を確認してください", error); setSaving(true); try { await Promise.all([saveMemberPreferences(CURRENT_USER.id, preferences), saveMemberAiConsents(CURRENT_USER.id, consents), saveMemberSafetyPreferences(CURRENT_USER.id, safety)]); await recordActivityEvent({ userId: CURRENT_USER.id, eventName: "profile_completed", entityType: "profile", entityId: CURRENT_USER.id }); Alert.alert("保存しました", "おすすめ設定とプライバシー設定を更新しました。", [{ text: "OK", onPress: () => router.back() }]); } finally { setSaving(false); } };
  const numberValue = (value: string) => { const parsed = Number(value.replace(/\D/g, "")); return Number.isFinite(parsed) ? Math.min(parsed, 200000) : 0; };
  return <ScreenContainer><View style={{ flexDirection: "row", alignItems: "center", padding: 16, borderBottomWidth: 0.5, borderBottomColor: colors.border }}><Pressable onPress={() => router.back()} style={{ padding: 4 }}><IconSymbol name="chevron.left" size={26} color={colors.foreground} /></Pressable><View style={{ flex: 1, marginLeft: 8 }}><Text style={{ fontSize: 20, fontWeight: "900", color: colors.foreground }}>AI・おすすめ設定</Text><Text style={{ fontSize: 11, color: colors.muted }}>約60〜90秒で設定できます</Text></View></View>
    <ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 130 }}>
      <View style={{ backgroundColor: "#FCEAF2", borderRadius: 15, padding: 14, marginBottom: 14 }}><Text style={{ fontSize: 14, fontWeight: "900", color: "#A63F69" }}>あなたに合うイベントを見つけやすくします</Text><Text style={{ fontSize: 12, lineHeight: 18, color: "#7B5262", marginTop: 5 }}>登録内容とイベント参加履歴を使ったルールベースのおすすめです。チャットやDMの本文は読み取りません。</Text></View>
      <Card title="1. 行きたいエリア" description="最大5個まで"><Chips options={AREA_OPTIONS} values={preferences.preferredAreas} max={5} onChange={(values) => setPreferences({ ...preferences, preferredAreas: values })} /></Card>
      <Card title="2. 好きな料理" description="最大5個まで"><Chips options={CUISINE_OPTIONS} values={preferences.favoriteCuisineKeys} max={5} onChange={(values) => setPreferences({ ...preferences, favoriteCuisineKeys: values })} /></Card>
      <Card title="3. 1回の希望予算"><View style={{ flexDirection: "row", alignItems: "center", gap: 8 }}><TextInput keyboardType="number-pad" value={preferences.budgetMinYen?.toString() ?? ""} onChangeText={(value) => setPreferences({ ...preferences, budgetMinYen: numberValue(value) })} placeholder="下限なし" style={{ flex: 1, backgroundColor: colors.background, borderRadius: 10, padding: 12, color: colors.foreground }} /><Text>〜</Text><TextInput keyboardType="number-pad" value={preferences.budgetMaxYen?.toString() ?? ""} onChangeText={(value) => setPreferences({ ...preferences, budgetMaxYen: numberValue(value) })} placeholder="上限なし" style={{ flex: 1, backgroundColor: colors.background, borderRadius: 10, padding: 12, color: colors.foreground }} /></View></Card>
      <Card title="4. 参加しやすい日時"><Text style={{ fontSize: 12, color: colors.muted, marginBottom: 7 }}>曜日</Text><Chips options={DAY_OPTIONS} values={preferences.availableDayTypes} onChange={(values) => setPreferences({ ...preferences, availableDayTypes: values as MemberPreferences["availableDayTypes"] })} /><Text style={{ fontSize: 12, color: colors.muted, marginTop: 14, marginBottom: 7 }}>時間帯</Text><Chips options={TIME_OPTIONS} values={preferences.availableTimeSlots} onChange={(values) => setPreferences({ ...preferences, availableTimeSlots: values as MemberPreferences["availableTimeSlots"] })} /></Card>
      <Card title="5. 好きな人数規模"><Chips options={SIZE_OPTIONS} values={preferences.preferredGroupSizes} onChange={(values) => setPreferences({ ...preferences, preferredGroupSizes: values as MemberPreferences["preferredGroupSizes"] })} /></Card>
      <Card title="6. 参加目的" description="最大3個まで"><Chips options={GOAL_OPTIONS} values={preferences.participationGoals} max={3} onChange={(values) => setPreferences({ ...preferences, participationGoals: values as MemberPreferences["participationGoals"] })} /><Text style={{ fontSize: 12, color: colors.muted, marginTop: 14, marginBottom: 7 }}>興味のあるイベント</Text><Chips options={EVENT_TYPE_OPTIONS} values={preferences.preferredEventTypes} onChange={(values) => setPreferences({ ...preferences, preferredEventTypes: values as MemberPreferences["preferredEventTypes"] })} /></Card>
      <Card title="AI利用への同意" description="すべて初期状態はオフです。必要な機能だけ選べます。"><ConsentRow label="イベントおすすめ" detail="登録した希望と参加履歴でイベントを並べ替えます" value={consents.eventRecommendation} onChange={(value) => setConsents({ ...consents, eventRecommendation: value })} /><ConsentRow label="会員マッチング" detail="将来のWelcome Table・仲間提案に利用します" value={consents.memberMatching} onChange={(value) => setConsents({ ...consents, memberMatching: value })} /><ConsentRow label="コンシェルジュの履歴利用" detail="相談履歴を次回提案に利用します" value={consents.conciergeHistory} onChange={(value) => setConsents({ ...consents, conciergeHistory: value })} /><ConsentRow label="匿名でサービス改善に利用" detail="個人が特定されない集計データのみ利用します" value={consents.anonymousImprovement} onChange={(value) => setConsents({ ...consents, anonymousImprovement: value })} /></Card>
      <Card title="アレルギー・安全情報" description="一般会員には公開されません。幹事への共有も本人が許可した場合だけです。"><TextInput value={safety.allergyText} onChangeText={(value) => setSafety({ ...safety, allergyText: value })} placeholder="アレルギー" placeholderTextColor={colors.muted} multiline style={{ minHeight: 52, backgroundColor: colors.background, borderRadius: 10, padding: 12, color: colors.foreground, marginBottom: 8 }} /><TextInput value={safety.dislikedFoods} onChangeText={(value) => setSafety({ ...safety, dislikedFoods: value })} placeholder="苦手な食材" placeholderTextColor={colors.muted} style={{ backgroundColor: colors.background, borderRadius: 10, padding: 12, color: colors.foreground, marginBottom: 8 }} /><TextInput value={safety.dietaryRestrictions} onChangeText={(value) => setSafety({ ...safety, dietaryRestrictions: value })} placeholder="食事制限（任意）" placeholderTextColor={colors.muted} style={{ backgroundColor: colors.background, borderRadius: 10, padding: 12, color: colors.foreground }} /><ConsentRow label="参加確定時に幹事へ共有" detail="安全管理に必要な情報だけ共有します" value={safety.shareWithOrganizer} onChange={(value) => setSafety({ ...safety, shareWithOrganizer: value })} /></Card>
    </ScrollView><View style={{ position: "absolute", left: 16, right: 16, bottom: 24 }}><Pressable disabled={saving} onPress={() => void save()} style={{ minHeight: 54, borderRadius: 16, backgroundColor: "#D65E8D", alignItems: "center", justifyContent: "center" }}><Text style={{ color: "#FFF", fontSize: 16, fontWeight: "900" }}>{saving ? "保存中…" : "設定を保存"}</Text></Pressable></View>
  </ScreenContainer>;
}
