import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useAuthContext } from "@/lib/auth-context";
import { isOperatorRole } from "@/lib/access-control";
import { confirmGiftLottery, getGiftApplications, getGiftCampaigns, saveGiftCampaigns, type GiftApplication, type GiftCampaign } from "@/lib/gift-campaign-store";
import type { MemberRank } from "@/constants/mock-data";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, Text, TextInput, View } from "react-native";
import { Image } from "expo-image";
import * as ImagePicker from "expo-image-picker";
import * as Api from "@/lib/_core/api";
import { deleteSharedGift, saveSharedGift } from "@/lib/benefits-api";
import { Platform } from "react-native";

const EMPTY_GIFT: GiftCampaign = { id: "", title: "", description: "", category: "gourmet", minimumRank: "regular", winnerCount: 1, deadline: "", status: "open", imageEmoji: "🎁" };
const RANKS: [MemberRank, string][] = [["regular", "全会員"], ["silver", "シルバー以上"], ["gold", "ゴールド以上"], ["platinum", "プラチナ"]];

export default function GiftCampaignManagerScreen() {
  const colors = useColors(); const router = useRouter(); const { user } = useAuthContext();
  const [items, setItems] = useState<GiftCampaign[]>([]); const [applications, setApplications] = useState<GiftApplication[]>([]);
  const [draft, setDraft] = useState<GiftCampaign>(EMPTY_GIFT); const [editingId, setEditingId] = useState<string | null>(null); const [showModal, setShowModal] = useState(false);
  const reload = async () => { const [gifts, apps] = await Promise.all([getGiftCampaigns(), getGiftApplications()]); setItems(gifts); setApplications(apps); return gifts; };
  useEffect(() => {
    if (!isOperatorRole(user?.role, user?.accessRole)) return;
    void reload();
  }, [user?.role, user?.accessRole]);
  if (!isOperatorRole(user?.role, user?.accessRole)) return <ScreenContainer className="p-6"><Text style={{ textAlign: "center", color: colors.muted, marginTop: 40 }}>運営メンバーのみアクセスできます</Text></ScreenContainer>;

  const openCreate = () => { setEditingId(null); setDraft({ ...EMPTY_GIFT, id: `gift_${Date.now()}`, deadline: new Date().toISOString().slice(0, 10) }); setShowModal(true); };
  const openEdit = (gift: GiftCampaign) => { setEditingId(gift.id); setDraft({ ...gift }); setShowModal(true); };
  const save = async () => { if (!draft.title.trim() || !draft.deadline || draft.winnerCount < 1) { Alert.alert("入力内容を確認", "タイトル・募集期限・当選人数は必須です。"); return; } try { const imageUrl = draft.imageUrl && !/^https?:\/\//i.test(draft.imageUrl) && !draft.imageUrl.startsWith("/api/") ? (await Api.uploadEventImage(draft.imageUrl)).imageUrl : draft.imageUrl; await saveSharedGift({ ...draft, imageUrl }); await reload(); setShowModal(false); Alert.alert(editingId ? "更新完了" : "作成完了", editingId ? "プレゼント企画を更新しました。" : "プレゼント企画を作成しました。"); } catch (error) { Alert.alert("保存できませんでした", error instanceof Error ? error.message : "通信状況を確認してください。"); } };
  const pickImage = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert("権限が必要です", "画像を選ぶには写真ライブラリへのアクセスを許可してください。"); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ImagePicker.MediaTypeOptions.Images, allowsEditing: true, aspect: [1, 1], quality: 0.8 }); if (!result.canceled && result.assets[0]) setDraft((current) => ({ ...current, imageUrl: result.assets[0].uri })); };
  const setStatus = async (gift: GiftCampaign) => { try { await saveSharedGift({ ...gift, status: gift.status === "open" ? "closed" : "open" }); await reload(); } catch (error) { Alert.alert("変更できませんでした", error instanceof Error ? error.message : "通信状況を確認してください。"); } };
  const remove = (gift: GiftCampaign) => { const execute = async () => { try { await deleteSharedGift(gift.id); await reload(); } catch (error) { Alert.alert("削除できませんでした", error instanceof Error ? error.message : "通信状況を確認してください。"); } }; if (Platform.OS === "web") { if (window.confirm(`${gift.title}を削除しますか？`)) void execute(); return; } Alert.alert("プレゼント企画を削除", `${gift.title}を削除しますか？`, [{ text: "キャンセル", style: "cancel" }, { text: "削除", style: "destructive", onPress: () => { void execute(); } }]); };
  const lottery = (gift: GiftCampaign) => { const pending = applications.filter((item) => item.campaignId === gift.id && item.result === "pending"); if (!pending.length) { Alert.alert("申込者がいません"); return; } Alert.alert("抽選を確定", `${pending.length}名から${Math.min(gift.winnerCount, pending.length)}名を抽選します。`, [{ text: "キャンセル", style: "cancel" }, { text: "抽選する", onPress: async () => { const result = await confirmGiftLottery(gift.id, gift.winnerCount); await reload(); const winners = result.filter((item) => item.campaignId === gift.id && item.result === "winner"); Alert.alert("抽選確定", `当選者：${winners.map((item) => item.memberName).join("、")}`); } }]); };

  return <ScreenContainer edges={["top", "left", "right"]}>
    <View style={{ flexDirection: "row", alignItems: "center", padding: 16, borderBottomWidth: 1, borderBottomColor: colors.border }}><Pressable onPress={() => router.back()}><IconSymbol name="arrow.left" size={22} color={colors.foreground} /></Pressable><Text style={{ flex: 1, fontSize: 20, fontWeight: "900", color: colors.foreground, marginLeft: 12 }}>プレゼント企画管理</Text><Pressable onPress={openCreate} style={{ flexDirection: "row", alignItems: "center", backgroundColor: "#E8A0BF", borderRadius: 18, paddingHorizontal: 12, paddingVertical: 8 }}><IconSymbol name="plus" size={14} color="#FFF" /><Text style={{ color: "#FFF", fontWeight: "800", marginLeft: 4 }}>作成</Text></Pressable></View>
    <View style={{ flexDirection: "row", gap: 10, padding: 16 }}><View style={{ flex: 1, backgroundColor: "#34C75918", borderRadius: 12, padding: 12, alignItems: "center" }}><Text style={{ fontSize: 22, fontWeight: "900", color: "#248A3D" }}>{items.filter((item) => item.status === "open").length}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>募集中</Text></View><View style={{ flex: 1, backgroundColor: "#8E8E9318", borderRadius: 12, padding: 12, alignItems: "center" }}><Text style={{ fontSize: 22, fontWeight: "900", color: colors.muted }}>{items.filter((item) => item.status === "closed").length}</Text><Text style={{ color: colors.muted, fontSize: 11 }}>募集終了</Text></View></View>
    <ScrollView contentContainerStyle={{ padding: 16, paddingTop: 0, paddingBottom: 40 }}>{items.map((gift) => { const applicants = applications.filter((item) => item.campaignId === gift.id); return <View key={gift.id} style={{ backgroundColor: colors.surface, borderRadius: 16, padding: 16, marginBottom: 12, opacity: gift.status === "closed" ? 0.65 : 1 }}>{gift.imageUrl ? <Image source={{ uri: gift.imageUrl }} style={{ width: 108, height: 108, borderRadius: 13, marginBottom: 10 }} contentFit="cover" /> : null}<View style={{ flexDirection: "row", alignItems: "center" }}><Text style={{ fontSize: 27, marginRight: 9 }}>{gift.imageEmoji}</Text><Text style={{ flex: 1, fontSize: 16, fontWeight: "900", color: colors.foreground }}>{gift.title}</Text><Text style={{ fontSize: 11, fontWeight: "800", color: gift.status === "open" ? "#248A3D" : colors.muted }}>{gift.status === "open" ? "募集中" : "募集終了"}</Text></View><Text style={{ color: colors.muted, lineHeight: 19, marginTop: 8 }}>{gift.description}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 8 }}>期限 {gift.deadline} ／ 申込 {applicants.length}名 ／ 当選 {gift.winnerCount}名</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 3 }}>対象 {RANKS.find(([rank]) => rank === gift.minimumRank)?.[1]}</Text><View style={{ flexDirection: "row", gap: 7, marginTop: 12 }}><Pressable onPress={() => openEdit(gift)} style={{ flex: 1, padding: 9, alignItems: "center", borderRadius: 9, backgroundColor: "#5D5C7418" }}><Text style={{ color: "#5D5C74", fontWeight: "800" }}>編集</Text></Pressable><Pressable onPress={() => { void setStatus(gift); }} style={{ flex: 1, padding: 9, alignItems: "center", borderRadius: 9, backgroundColor: gift.status === "open" ? "#FF950018" : "#34C75918" }}><Text style={{ color: gift.status === "open" ? "#B06C21" : "#248A3D", fontWeight: "800" }}>{gift.status === "open" ? "終了" : "再開"}</Text></Pressable><Pressable onPress={() => remove(gift)} style={{ flex: 1, padding: 9, alignItems: "center", borderRadius: 9, backgroundColor: "#FF3B3018" }}><Text style={{ color: "#FF3B30", fontWeight: "800" }}>削除</Text></Pressable></View>{gift.status === "open" ? <Pressable onPress={() => lottery(gift)} style={{ marginTop: 8, padding: 10, alignItems: "center", borderRadius: 9, backgroundColor: "#E8A0BF" }}><Text style={{ color: "#FFF", fontWeight: "900" }}>抽選を確定</Text></Pressable> : null}</View>; })}</ScrollView>
    <Modal visible={showModal} animationType="slide" presentationStyle="formSheet" onRequestClose={() => setShowModal(false)}><View style={{ flex: 1, backgroundColor: colors.background }}><View style={{ flexDirection: "row", padding: 16, alignItems: "center", borderBottomWidth: 1, borderBottomColor: colors.border }}><Pressable onPress={() => setShowModal(false)}><Text style={{ color: colors.muted }}>キャンセル</Text></Pressable><Text style={{ flex: 1, textAlign: "center", fontWeight: "900", fontSize: 17, color: colors.foreground }}>{editingId ? "プレゼント企画編集" : "プレゼント企画作成"}</Text><Pressable onPress={() => { void save(); }}><Text style={{ color: "#E8A0BF", fontWeight: "900" }}>保存</Text></Pressable></View><ScrollView contentContainerStyle={{ padding: 16, paddingBottom: 40 }}>
      <Text style={{ color: colors.muted, fontWeight: "700", fontSize: 12, marginBottom: 6 }}>画像（正方形）</Text><Pressable onPress={() => { void pickImage(); }} style={{ width: 190, height: 190, alignSelf: "center", borderRadius: 14, overflow: "hidden", backgroundColor: colors.surface, borderWidth: 1, borderStyle: draft.imageUrl ? "solid" : "dashed", borderColor: colors.border, alignItems: "center", justifyContent: "center", marginBottom: 8 }}>{draft.imageUrl ? <Image source={{ uri: draft.imageUrl }} style={{ width: "100%", height: "100%" }} contentFit="cover" /> : <><IconSymbol name="photo.fill" size={31} color={colors.muted} /><Text style={{ color: colors.muted, marginTop: 7, fontSize: 12 }}>正方形の画像を選択</Text></>}</Pressable>{draft.imageUrl ? <Pressable onPress={() => setDraft({ ...draft, imageUrl: undefined })} style={{ alignSelf: "center", padding: 7, marginBottom: 8 }}><Text style={{ color: "#FF3B30", fontWeight: "700", fontSize: 12 }}>画像を削除</Text></Pressable> : null}
      <Text style={{ color: colors.muted, fontWeight: "700", fontSize: 12, marginBottom: 6 }}>アイコン</Text><TextInput value={draft.imageEmoji} onChangeText={(imageEmoji) => setDraft({ ...draft, imageEmoji })} maxLength={4} style={{ backgroundColor: colors.surface, borderRadius: 10, padding: 12, fontSize: 22, color: colors.foreground, marginBottom: 14 }} />
      {([['title', 'タイトル', 'プレゼント企画名'], ['description', '説明', '企画内容'], ['deadline', '募集期限（YYYY-MM-DD）', '2026-12-31']] as const).map(([key, label, placeholder]) => <View key={key}><Text style={{ color: colors.muted, fontWeight: "700", fontSize: 12, marginBottom: 6 }}>{label}</Text><TextInput value={draft[key]} onChangeText={(value) => setDraft({ ...draft, [key]: value })} placeholder={placeholder} placeholderTextColor={colors.muted} multiline={key === "description"} style={{ backgroundColor: colors.surface, borderRadius: 10, padding: 12, fontSize: 15, color: colors.foreground, marginBottom: 14, minHeight: key === "description" ? 80 : undefined, textAlignVertical: key === "description" ? "top" : "auto" }} /></View>)}
      <Text style={{ color: colors.muted, fontWeight: "700", fontSize: 12, marginBottom: 6 }}>当選人数</Text><TextInput value={String(draft.winnerCount)} onChangeText={(value) => setDraft({ ...draft, winnerCount: Math.max(0, Number(value.replace(/\D/g, "")) || 0) })} keyboardType="number-pad" style={{ backgroundColor: colors.surface, borderRadius: 10, padding: 12, fontSize: 15, color: colors.foreground, marginBottom: 14 }} />
      <Text style={{ color: colors.muted, fontWeight: "700", fontSize: 12, marginBottom: 7 }}>カテゴリ</Text><View style={{ flexDirection: "row", gap: 8, marginBottom: 16 }}>{([['gourmet', 'グルメ'], ['non_gourmet', 'グルメ以外']] as const).map(([category, label]) => <Pressable key={category} onPress={() => setDraft({ ...draft, category })} style={{ flex: 1, alignItems: "center", padding: 10, borderRadius: 10, backgroundColor: draft.category === category ? "#5D5C74" : colors.surface }}><Text style={{ color: draft.category === category ? "#FFF" : colors.foreground, fontWeight: "800" }}>{label}</Text></Pressable>)}</View>
      <Text style={{ color: colors.muted, fontWeight: "700", fontSize: 12, marginBottom: 7 }}>申込可能ランク</Text><View style={{ flexDirection: "row", flexWrap: "wrap", gap: 7 }}>{RANKS.map(([rank, label]) => <Pressable key={rank} onPress={() => setDraft({ ...draft, minimumRank: rank })} style={{ paddingHorizontal: 11, paddingVertical: 9, borderRadius: 10, backgroundColor: draft.minimumRank === rank ? "#E8A0BF" : colors.surface }}><Text style={{ color: draft.minimumRank === rank ? "#FFF" : colors.foreground, fontWeight: "800", fontSize: 11 }}>{label}</Text></Pressable>)}</View>
    </ScrollView></View></Modal>
  </ScreenContainer>;
}
